name: CI

on:
  push:
    branches:
      - main
      - '*.x'
    tags:
      - '*'
  pull_request:
    branches:
      - main
  schedule:
    # Weekly Monday 9AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 9 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@924441154cf3053034c6513d5e06c69d262fb9a6  # v1.13.0
    with:
      envs: |
        - linux: check-style
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@924441154cf3053034c6513d5e06c69d262fb9a6  # v1.13.0
    with:
      libraries: |
        brew:
          - eigen
          - fftw
      setenv: |
        FFTW_DIR: /opt/homebrew/opt/fftw/lib/

      envs: |
        - linux: py310-oldestdeps-cov-xdist
        - linux: py310-xdist
        - linux: py311-xdist
        - linux: py3-xdist
        - macos: py3-xdist
        - linux: py3-pyargs-xdist
        - linux: py3-cov-xdist
          coverage: codecov
